package services.set.gov.py.rucas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.5-b04 Generated
 * source version: 2.1
 *
 */
@WebServiceClient(name = "SessionManagementService", targetNamespace = "http://py.gov.set.services/rucas/", wsdlLocation = "http://190.211.240.65:8087/rucas/SessionManagementEJB?wsdl")
public class SessionManagementService
        extends Service {

    private final static URL SESSIONMANAGEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SESSIONMANAGEMENTSERVICE_EXCEPTION;
    private final static QName SESSIONMANAGEMENTSERVICE_QNAME = new QName("http://py.gov.set.services/rucas/", "SessionManagementService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://190.211.240.65:8087/rucas/SessionManagementEJB?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SESSIONMANAGEMENTSERVICE_WSDL_LOCATION = url;
        SESSIONMANAGEMENTSERVICE_EXCEPTION = e;
    }

    public SessionManagementService() {
        super(__getWsdlLocation(), SESSIONMANAGEMENTSERVICE_QNAME);
    }

    public SessionManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SessionManagementService(URL wsdlLocation) {
        super(wsdlLocation, SESSIONMANAGEMENTSERVICE_QNAME);
    }

    /**
     *
     * @return returns SessionManagement
     */
    @WebEndpoint(name = "SessionManagementPort")
    public SessionManagement getSessionManagementPort() {
        return super.getPort(new QName("http://py.gov.set.services/rucas/", "SessionManagementPort"), SessionManagement.class);
    }

    /**
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to
     * configure on the proxy. Supported features not in the
     * <code>features</code> parameter will have their default values.
     * @return returns SessionManagement
     */
    @WebEndpoint(name = "SessionManagementPort")
    public SessionManagement getSessionManagementPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://py.gov.set.services/rucas/", "SessionManagementPort"), SessionManagement.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SESSIONMANAGEMENTSERVICE_EXCEPTION != null) {
            throw SESSIONMANAGEMENTSERVICE_EXCEPTION;
        }
        return SESSIONMANAGEMENTSERVICE_WSDL_LOCATION;
    }

}
