
package services.set.gov.py.rucas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b04 
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SessionManagement", targetNamespace = "http://py.gov.set.services/rucas/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    py.gov.set.rucas.beans.components.jaws.ObjectFactory.class,
    py.gov.set.rucas.beans.connect.jaws.ObjectFactory.class,
    py.gov.set.rucas.beans.error.jaws.ObjectFactory.class,
    py.gov.set.rucas.beans.jaws.ObjectFactory.class,
    services.set.gov.py.rucas.ObjectFactory.class
})
public interface SessionManagement {


    /**
     * 
     * @param loginMethod
     * @param cryptMethod
     * @param appInfo
     * @return
     *     returns services.set.gov.py.rucas.RUCASConnectResponse
     */
    @WebMethod(operationName = "RUCASConnect")
    @WebResult(name = "result", partName = "result")
    public RUCASConnectResponse rucasConnect(
        @WebParam(name = "appInfo", partName = "appInfo")
        AppInfo appInfo,
        @WebParam(name = "loginMethod", partName = "loginMethod")
        LoginMethod loginMethod,
        @WebParam(name = "cryptMethod", partName = "cryptMethod")
        CryptMethod cryptMethod);

    /**
     * 
     * @param loginMethod
     * @param cryptMethod
     * @return
     *     returns services.set.gov.py.rucas.RUCASLoginResponse
     */
    @WebMethod(operationName = "RUCASLogin")
    @WebResult(name = "result", partName = "result")
    public RUCASLoginResponse rucasLogin(
        @WebParam(name = "loginMethod", partName = "loginMethod")
        LoginMethod loginMethod,
        @WebParam(name = "cryptMethod", partName = "cryptMethod")
        CryptMethod cryptMethod);

    /**
     * 
     * @return
     *     returns services.set.gov.py.rucas.ClientSystem
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public ClientSystem getClientSystem();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public String getCurrentVersion();

}
