
package services.set.gov.py.rucas.era;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b04 
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EraManagement", targetNamespace = "http://py.gov.set.services/rucas/era")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    py.gov.set.rucas.exception.jaws.ObjectFactory.class,
    services.set.gov.py.rucas.era.ObjectFactory.class
})
public interface EraManagement {


    /**
     * 
     * @param xmlDDJJ
     * @param sessionId
     * @param nroHash
     * @return
     *     returns java.lang.String
     * @throws RucasWsException_Exception
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public String consultarDDJJ(
        @WebParam(name = "sessionId", partName = "sessionId")
        String sessionId,
        @WebParam(name = "xmlDDJJ", partName = "xmlDDJJ")
        String xmlDDJJ,
        @WebParam(name = "nroHash", partName = "nroHash")
        String nroHash)
        throws RucasWsException_Exception
    ;

    /**
     * 
     * @param xmlDDJJ
     * @param sessionId
     * @param nroHash
     * @return
     *     returns java.lang.String
     * @throws RucasWsException_Exception
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public String guardarDDJJ(
        @WebParam(name = "sessionId", partName = "sessionId")
        String sessionId,
        @WebParam(name = "xmlDDJJ", partName = "xmlDDJJ")
        String xmlDDJJ,
        @WebParam(name = "nroHash", partName = "nroHash")
        String nroHash)
        throws RucasWsException_Exception
    ;

}
