package services.set.gov.py.rucas.era;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.5-b04 Generated
 * source version: 2.1
 *
 */
@WebServiceClient(name = "EraManagementService", targetNamespace = "http://py.gov.set.services/rucas/era", wsdlLocation = "http://190.211.240.65:8087/rucas/EraManagementEJB?wsdl")
public class EraManagementService
        extends Service {

    private final static URL ERAMANAGEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException ERAMANAGEMENTSERVICE_EXCEPTION;
    private final static QName ERAMANAGEMENTSERVICE_QNAME = new QName("http://py.gov.set.services/rucas/era", "EraManagementService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://190.211.240.65:8087/rucas/EraManagementEJB?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ERAMANAGEMENTSERVICE_WSDL_LOCATION = url;
        ERAMANAGEMENTSERVICE_EXCEPTION = e;
    }

    public EraManagementService() {
        super(__getWsdlLocation(), ERAMANAGEMENTSERVICE_QNAME);
    }

    public EraManagementService(URL wsdl) {
        super(wsdl, ERAMANAGEMENTSERVICE_QNAME);
    }

    public EraManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return returns EraManagement
     */
    @WebEndpoint(name = "EraManagementPort")
    public EraManagement getEraManagementPort() {
        return super.getPort(new QName("http://py.gov.set.services/rucas/era", "EraManagementPort"), EraManagement.class);
    }

    /**
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to
     * configure on the proxy. Supported features not in the
     * <code>features</code> parameter will have their default values.
     * @return returns EraManagement
     */
    @WebEndpoint(name = "EraManagementPort")
    public EraManagement getEraManagementPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://py.gov.set.services/rucas/era", "EraManagementPort"), EraManagement.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ERAMANAGEMENTSERVICE_EXCEPTION != null) {
            throw ERAMANAGEMENTSERVICE_EXCEPTION;
        }
        return ERAMANAGEMENTSERVICE_WSDL_LOCATION;
    }

}
