
package services.set.gov.py.rucas.era;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b04 
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "RucasWsException", targetNamespace = "http://py.gov.set.services/rucas/era")
public class RucasWsException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RucasWsException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public RucasWsException_Exception(String message, RucasWsException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public RucasWsException_Exception(String message, RucasWsException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: services.set.gov.py.rucas.era.RucasWsException
     */
    public RucasWsException getFaultInfo() {
        return faultInfo;
    }

}
