package services.set.gov.py.rucas.pagos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.5-b04 Generated
 * source version: 2.1
 *
 */
@WebServiceClient(name = "PagoElectronicoManagementService", targetNamespace = "http://py.gov.set.services/rucas/pagos", wsdlLocation = "http://190.211.240.65:8087/rucas/PagoElectronicoManagementEJB?wsdl")
public class PagoElectronicoManagementService
        extends Service {

    private final static URL PAGOELECTRONICOMANAGEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PAGOELECTRONICOMANAGEMENTSERVICE_EXCEPTION;
    private final static QName PAGOELECTRONICOMANAGEMENTSERVICE_QNAME = new QName("http://py.gov.set.services/rucas/pagos", "PagoElectronicoManagementService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://190.211.240.65:8087/rucas/PagoElectronicoManagementEJB?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAGOELECTRONICOMANAGEMENTSERVICE_WSDL_LOCATION = url;
        PAGOELECTRONICOMANAGEMENTSERVICE_EXCEPTION = e;
    }

    public PagoElectronicoManagementService() {
        super(__getWsdlLocation(), PAGOELECTRONICOMANAGEMENTSERVICE_QNAME);
    }

    public PagoElectronicoManagementService(URL wsdlLocation) {
        super(wsdlLocation, PAGOELECTRONICOMANAGEMENTSERVICE_QNAME);
    }

    public PagoElectronicoManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return returns PagoElectronicoManagement
     */
    @WebEndpoint(name = "PagoElectronicoManagementPort")
    public PagoElectronicoManagement getPagoElectronicoManagementPort() {
        return super.getPort(new QName("http://py.gov.set.services/rucas/pagos", "PagoElectronicoManagementPort"), PagoElectronicoManagement.class);
    }

    /**
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to
     * configure on the proxy. Supported features not in the
     * <code>features</code> parameter will have their default values.
     * @return returns PagoElectronicoManagement
     */
    @WebEndpoint(name = "PagoElectronicoManagementPort")
    public PagoElectronicoManagement getPagoElectronicoManagementPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://py.gov.set.services/rucas/pagos", "PagoElectronicoManagementPort"), PagoElectronicoManagement.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAGOELECTRONICOMANAGEMENTSERVICE_EXCEPTION != null) {
            throw PAGOELECTRONICOMANAGEMENTSERVICE_EXCEPTION;
        }
        return PAGOELECTRONICOMANAGEMENTSERVICE_WSDL_LOCATION;
    }

}
