
package py.com.konecta.redcobros.wsc.clases;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "RedFacadeImpl", targetNamespace = "http://impl.ejb.redcobros.konecta.com.py/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RedFacadeImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Long>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProximoRangoOrden", targetNamespace = "http://impl.ejb.redcobros.konecta.com.py/", className = "py.com.konecta.redcobros.wsc.clases.GetProximoRangoOrden")
    @ResponseWrapper(localName = "getProximoRangoOrdenResponse", targetNamespace = "http://impl.ejb.redcobros.konecta.com.py/", className = "py.com.konecta.redcobros.wsc.clases.GetProximoRangoOrdenResponse")
    public List<Long> getProximoRangoOrden(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0)
        throws Exception_Exception
    ;

}
