
package py.com.konecta.redcobros.wsc.clases;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RedFacadeImplService", targetNamespace = "http://impl.ejb.redcobros.konecta.com.py/", wsdlLocation = "http://localhost:10492/RedFacadeImplService/RedFacadeImpl?wsdl")
public class RedFacadeImplService
    extends Service
{


    private final static Logger logger = Logger.getLogger(py.com.konecta.redcobros.wsc.clases.RedFacadeImplService.class.getName());


    public static RedFacadeImplService getInstance(String urlServidor) throws java.lang.Exception {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = py.com.konecta.redcobros.wsc.clases.RedFacadeImplService.class.getResource(".");
            url = new URL(baseUrl, urlServidor+"/RedFacadeImplService/RedFacadeImpl?wsdl");
            QName qName=new QName("http://impl.ejb.redcobros.konecta.com.py/", "RedFacadeImplService");
            logger.info("creando conexion al ws "+urlServidor);
            System.out.println("creando conexion al ws "+urlServidor);
            return new RedFacadeImplService(url, qName);
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/RedFacadeImplService/RedFacadeImpl?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
            throw new java.lang.Exception("No se puede consultar el ws",e);
        }
    }

    public RedFacadeImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns RedFacadeImpl
     */
    @WebEndpoint(name = "RedFacadeImplPort")
    public RedFacadeImpl getRedFacadeImplPort() {
        return super.getPort(new QName("http://impl.ejb.redcobros.konecta.com.py/", "RedFacadeImplPort"), RedFacadeImpl.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RedFacadeImpl
     */
    @WebEndpoint(name = "RedFacadeImplPort")
    public RedFacadeImpl getRedFacadeImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.ejb.redcobros.konecta.com.py/", "RedFacadeImplPort"), RedFacadeImpl.class, features);
    }

}
